version: "3.7"

services:
  taskmaster:
    build: .
    image: ide-api
    restart: on-failure
    ports:
    - "3000:3000"
    env_file:
      - .env

  redis:
    image: redis:4-alpine
    restart: on-failure
    ports:
      - "6379:6379"
