name: Build and Deploy

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  APP_SIGNING_SECRET: ${{ secrets.APP_SIGNING_SECRET }}
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IAM_SERVICE_ACCOUNT_EMAIL: ${{ secrets.IAM_SERVICE_ACCOUNT_EMAIL }}
  CLOUD_SCHEDULER_SA_EMAIL: ${{ secrets.CLOUD_SCHEDULER_SA_EMAIL }}
  PUBSUB_OAUTH_AUD_CLAIM: ${{ secrets.PUBSUB_OAUTH_AUD_CLAIM }}
  PUBSUB_TOPIC_NAME: ${{ secrets.PUBSUB_TOPIC_NAME }}
  PUBSUB_VERIFICATION_TOKEN: ${{ secrets.PUBSUB_VERIFICATION_TOKEN }}
  GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
  GCS_BUCKET_PATH: ${{ secrets.GCS_BUCKET_PATH }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build Docker Image
        run: ./scripts/build-docker-image.sh

      - name: Push Docker Image to Docker Hub
        run: ./scripts/push-docker-image.sh

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Deploy to Cloud Run
        run: ./scripts/terraform-apply.sh
